question_data = [
    {"text": "The HTML5 standard was published in 2014.", "answer": "True", "incorrect_answers": ["False"]},
    {"text": "The common software-programming acronym I18N comes from the term Interlocalization.", "answer": "False"},
    {"text": "The first computer bug was formed by faulty wires.", "answer": "False"},
    {"text": "FLAC stands for Free Lossless Audio Condenser", "answer": "False"},
    {"text": "The very first recorded computer 'bug' was a moth found inside a Harvard Mark II computer.",
        "answer": "True"},
    {"text": "All program codes have to be compiled into an executable file in order to be run. This file can then be "
             "executed on any machine.", "answer": "False"},
    {"text": "Linus Torvalds created Linux and Git.", "answer": "True", "incorrect_answers": ["False"]},
    {"text": "The programming language Python is based off a modified version of JavaScript.", "answer": "False"},
    {"text": "The logo for Snapchat is a Bell.", "answer": "False", "incorrect_answers": ["True"]},
    {"text": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "answer": "False"}, {"text": "Windows NT is a monolithic kernel.", "answer": "False"},
    {"text": "To bypass US Munitions Export Laws, the creator of the PGP published all the source code in book form. ",
        "answer": "True"},
    {"text": "RAM stands for Random Access Memory.", "answer": "True", "incorrect_answers": ["False"]},
    {"text": "Ada Lovelace is often considered the first computer programmer.", "answer": "True"},
    {"text": "MacOS is based on Linux.", "answer": "False", "incorrect_answers": ["True"]},
    {"text": "The open source program Redis is a relational database server.", "answer": "False"},
    {"text": "AMD created the first consumer 64-bit processor.", "answer": "True"},
    {"text": "DHCP stands for Dynamic Host Configuration Port.", "answer": "False"},
    {"text": "HTML stands for Hypertext Markup Language.", "answer": "True"},
    {"text": "In most programming languages, the operator ++ is equivalent to the statement += 1.",
        "answer": "True"},
    {"text": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
        "answer": "False"},
    {"text": "Early RAM was directly seated onto the motherboard and could not be easily removed.", "answer": "True"},
    {"text": "Time on Computers is measured via the EPOX System.", "answer": "False"},
    {"text": "The Windows 7 operating system has six main editions.", "answer": "True"},
    {"text": "The Windows ME operating system was released in the year 2000.", "answer": "True"},
    {"text": "The Nvidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
        "answer": "False"},
    {"text": "The first dual-core CPU was the Intel Pentium D.", "answer": "False"},
    {"text": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
        "answer": "False"},
    {"text": "It's not possible to format a write-protected DVD-R Hard Disk.", "answer": "True"},
    {"text": "Linux was first created as an alternative to Windows XP.", "answer": "False"},
    {"text": "Android versions are named in alphabetical order.", "answer": "True"},
    {"text": "Linus Sebastian is the creator of the Linux kernel, which went on to be used in Linux, Android, and Chrome OS.",
        "answer": "False"},
    {"text": "A Boolean value of 0 represents which of these words?", "answer": "False"},
    {"text": "The Python programming language gets its name from the British comedy group Monty Python",
        "answer": "True"},
    {"text": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.", "answer": "True"}]
